name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        php:
          - 7.4
          - 7.3
          - 7.2
          - 7.1
          - 7.0
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zlib
          coverage: xdebug
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
